version: '3.4'

services:
  db:
    image: postgres:latest
    ports:
      - 9432:5432
    environment:
      - POSTGRES_DB=badminton-brest-bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass123

  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules/
    ports:
      - 9000:9000
    depends_on:
      - db
