---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ex-split-bot-configmap
data:
  default_price: '12'

---
apiVersion: v1
kind: Secret
metadata:
  name: ex-split-bot-secret
data:
  telegram_token: ''
  app_token: ''
  database_url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpkYnBhc3MxMjNAcG9zdGdyZXM6NTQzMi9leC1zcGxpdC1ib3Q=
  rollbar_access_token: ''

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:10.4
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: ex-split-bot
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: dbpass123
            - name: PGDATA
              value: '/var/lib/postgresql/data/dbfiles'
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-split-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex-split-bot
  template:
    metadata:
      labels:
        app: ex-split-bot
    spec:
      containers:
        - image: zinovik/ex-split-bot:stable
          name: ex-split-bot
          env:
            - name: DEFAULT_PRICE
              valueFrom:
                configMapKeyRef:
                  name: ex-split-bot-configmap
                  key: default_price
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ex-split-bot-secret
                  key: telegram_token
            - name: APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ex-split-bot-secret
                  key: app_token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ex-split-bot-secret
                  key: database_url
            - name: ROLLBAR_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ex-split-bot-secret
                  key: rollbar_access_token

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    dev.okteto.com/auto-ingress: 'true'
spec:
  type: ClusterIP
  ports:
    - name: 'ex-split-bot'
      port: 9000
  selector:
    app: ex-split-bot
