version: '3.4'

services:
  database_postgresql:
    image: postgres:latest
    ports:
      - 9432:5432
    environment:
      - POSTGRES_DB=ex-split-bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass123
